### PR TITLE
BA-1718-001: CCO by-laws update to reflect current practices.

### PR DESCRIPTION
**Pull request by laurengulland**
There are multiple places in the by-laws where we were being more efficient (e.g. rather than sending a weekly spending update to the VP for Finance, it's in the shared google drive. As long as the VP for Finance has easy access to these spreadsheets as the updated by-laws state, it's a much better system). Other small changes include wording clarification on online purchases (not all online purchases are made through amazon.com), and slight changes on the individual vs. club spending ban. We updated this to reflect the current practices which inflict punitive measures on the individual for failing to submit requests or receipts, which we think is a better measure than full club spending bans, and also ensures that the person at fault can't do the same for another club. (Again, this is a current practice as is taught in club spending trainings, which are led by the Director and Assistant Director of CCO along side the VP for Finance.

Love, 
2016-2017 CCO <3

### CODE REVIEW

**Comment by newsch** [comment]
@sammyers we should address this and the other amendments at the next sg meeting on February 7th. @laurengulland, @yjiang0929, and I have been discussing some changes to spending and found that they were already proposed a year ago.

**Comment by laurengulland** [comment]
@sammyers Yichen, Evan, and I just updated this amendment to consolidate from Pull Request #30 as well. Can we bring this up at the March SG meeting for discussion?

**Comment by mitchcieminski** [comment]
(Re: Line 480) So when we were drafting this section, we intended for the the general membership of CCO to actually include every student leader (not just of clubs and orgs) because _there is no other way to contact every single student leader_. Our intended use case of the CCO membership was this:
 
**Random Person**
>man I wish every student leader knew ____ (how to reimburse with the school, when we're having club fair, whatever)
**Random Person 2**
>You should contact the Director of Clubs and Orgs
**Director of Clubs and Orgs**
>Yeah I can email the CCO general membership
**Every leader of a student organization**
>Now we know this information

Now maybe this is an unnecessary system at this point in time. Maybe the SG president is better suited to be the point person for such contact. But that was the idea.

**Comment by newsch** [comment]
@mitchcieminski you mean everyone from project team leaders to student-run course leaders to shop NINJAs?

**Comment by mitchcieminski** [comment]
Yeah, I do. There's no other good way to really contact everybody.

Maybe this should be a separate role. Maybe it's taken by Ashlee. Still,
such was our intent.

**Pull request merged**
